version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:stable
    branches:
      only: master
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - run:
          name: Run the application tests
          command: flutter test
      - run:
          name: Build the Android version
          command: flutter build appbundle --target-platform android-arm,android-arm64,android-x64

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.aab
